# Generated by Django 4.2.7 on 2024-01-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/media/uploads/')),
                ('title', models.CharField(max_length=300)),
                ('descriptions', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagory.categorysmodel')),
            ],
        ),
    ]
